version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000 --nostatic"
    env_file:
      - .env
    environment:
      - DEBUG=1
    volumes:
      - ./ekvatour:/server
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    env_file:
      - .env
    ports:
      - 5432:5432

