version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./ekvatour/mediafiles:/nginx/media
      - ./ekvatour/staticfiles:/nginx/static

  web:
    build: .
    command: gunicorn config.wsgi -c config/gunicorn.py
    env_file:
      - .env
    volumes:
      - ./ekvatour:/server
    depends_on:
      - db
      - redis
  db:
    image: postgres:11
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
  redis:
    image: redis:alpine

volumes:
  db-data:
    driver: local
