version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ekvatour/mediafiles:/nginx/media
      - ./ekvatour/staticfiles:/nginx/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx:/etc/nginx/conf.d/
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  web:
    build: .
    command: gunicorn config.wsgi -c config/gunicorn.py
    env_file:
      - .env
    volumes:
      - ./ekvatour:/server
    depends_on:
      - db
      - redis
  db:
    image: postgres:11
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
  redis:
    image: redis:alpine

volumes:
  db-data:
    driver: local
