version: '3'

services:
  web:
    build: .
    command: python /server/manage.py runserver 0.0.0.0:8000
    env_file:
    - .env
    volumes:
    - ./ekvatour:/server
    ports:
    - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    env_file:
    - .env
    ports:
    - 5432:5432

