version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ekvatour/mediafiles:/nginx/media
      - ./ekvatour/staticfiles:/nginx/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      nginx_net:
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      nginx_net:
  web:
    build: .
    command: gunicorn config.wsgi -c config/gunicorn.py
    env_file:
      - .env
    volumes:
      - ./ekvatour:/server
    depends_on:
      - db
      - redis
  db:
    image: postgres:11
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
  redis:
    image: redis:alpine

volumes:
  db-data:
    driver: local

networks:
  nginx_net:
    name: nginx_net
