version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - server
    ports:
      - 80:80
    volumes:
      - ./ekvatour/mediafiles:/nginx/media
      - ./ekvatour/staticfiles:/nginx/static
  server:
    build: .
    command: gunicorn config.wsgi -c config/gunicorn.py
    env_file:
      - .env
    volumes:
      - ./ekvatour:/server
    depends_on:
      - db
    restart: unless-stopped
  celery:
    build: .
    command: celery -A config worker -l info
    env_file:
      - .env
    volumes:
      - ./ekvatour:/server
    depends_on:
      - db
      - redis
  db:
    image: postgres:11
    volumes:
    - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
  redis:
    image: redis:alpine

