# Generated by Django 3.0.7 on 2020-06-06 08:42

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Города',
            },
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('about', ckeditor.fields.RichTextField(verbose_name='О стране')),
                ('flag', models.ImageField(upload_to='country_flags/', verbose_name='Изображение флага')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст новости')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='TourOptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100, unique=True, verbose_name='Название опции')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.CreateModel(
            name='TourTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название направления')),
            ],
            options={
                'verbose_name': 'Тип тура',
                'verbose_name_plural': 'Типы туров',
            },
        ),
        migrations.CreateModel(
            name='TourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_created', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Время создания тура')),
                ('tour_type', models.CharField(choices=[('H', 'Горчий тур'), ('O', 'Обычный тур')], max_length=1, verbose_name='Тип тура')),
                ('departure_date', models.DateField(verbose_name='Дата вылета')),
                ('arrival_date', models.DateField(verbose_name='Дата прилета')),
                ('departure_time', models.TimeField(verbose_name='Время вылета')),
                ('number_of_adults', models.PositiveSmallIntegerField(verbose_name='Количество взрослых')),
                ('number_of_child', models.PositiveSmallIntegerField(verbose_name='Количество детей')),
                ('tour_category', models.CharField(choices=[('SC', 'SC'), ('HV2', 'HV2'), ('HV1', 'HV1'), ('5', '5*'), ('4', '4*'), ('3', '3*')], max_length=3, verbose_name='Категория тура')),
                ('tour_nutrition', models.CharField(choices=[('AI', 'AI'), ('BB', 'BB'), ('FB', 'FB'), ('HB', 'HB'), ('RO', 'RO')], max_length=2, verbose_name='Питание')),
                ('image', models.ImageField(upload_to='tour_images/', verbose_name='Изображение тура')),
                ('hotel_name', models.CharField(default='NoName', max_length=200, verbose_name='Название отеля')),
                ('accommodation_number', models.CharField(default='NoName', max_length=200, verbose_name='Номер размещения')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Цена тура')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.CityModel', verbose_name='Город отправления')),
                ('tour_options', models.ManyToManyField(related_name='tours', to='tour.TourOptionModel')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Время создания')),
                ('star', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='содержание отзыва')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.TourModel', verbose_name='на какой тур')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReservedTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный тур')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.TourModel', verbose_name='зарезервированный тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_tours', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Зарезервированный тур',
                'verbose_name_plural': 'Зарезервированные туры',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='list_image/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tour.CountryModel')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.AddField(
            model_name='citymodel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='tour.CountryModel', verbose_name='Страна'),
        ),
    ]
